
export const steps = [
  {
    emoji: "✨",
    progressTitle: "STEP 1 여행지 ",
    progressSubTitle: "destination",
    title: "어디로 떠나고 싶으세요?",
    subTitle: "일정에 포함될 수 있도록 반영해드려요.",
    content: "stepPage1",
  },
  {
    emoji: "🗺️",
    progressTitle: "STEP 2 필수 코스",
    progressSubTitle: "required_places",
    title: "꼭 가야 하는 장소가 있나요?",
    subTitle: "일정에 포함될 수 있도록 반영해드려요.",
    content: "stepPage2",
  },
  {
    emoji: "📅",
    progressTitle: "STEP 3 여행기간 ",
    progressSubTitle: "duration",
    title: "여행 기간을 선택하세요.",
    subTitle: "당일치기부터 장기여행까지, 원하는 일정을 고를 수 있어요.",
    content: "stepPage3",
  },
  {
    emoji: "👥",
    progressTitle: "STEP 4 동행자",
    progressSubTitle: "companion",
    title: "누구와 함께 가시나요?",
    subTitle: "동행에 맞춰 최적의 일정을 추천해드려요.",
    content: "stepPage4",
  },
  {
    emoji: "🤩",
    progressTitle: "STEP 5 여행스타일",
    progressSubTitle: "style",
    title: "어떤 스타일의 여행을 원하시나요?",
    subTitle: "취향에 맞춰 일정을 구성해드려요.",
    content: "stepPage5",
  },
  {
    emoji: "🕒",
    progressTitle: "STEP 6 일정 개수",
    progressSubTitle: "schedule_count",
    title: "일정을 어떻게 만들어드릴까요?",
    subTitle: "여유로운 여행부터 빽빽한 일정까지, 원하는 스타일을 선택하세요.",
    content: "stepPage6",
  },
  {
    emoji: "💰",
    progressTitle: "STEP 7 예산",
    progressSubTitle: "budget",
    title: "예산을 정해주세요. ",
    subTitle: "예산에 맞춰 최적의 여행지를 추천해드려요.",
    content: "stepPage7",
  },
  {
    emoji: "➕",
    progressTitle: "STEP 8 추가사항",
    title: "추가로 원하는 사항이 있나요?",
    subTitle: "특별히 고려해야 할 점이 있다면 입력해주세요.",
    content: "stepPage8",
  },
];
